--installation
INSERT INTO TINSTALLATION (NUM_INS, DATE_INS, ADRESSE_INS, CP_INS, VILLE_INS, INSTALLATEUR_INS, TYPE_INS, FKCABLE_INS, FKDISJONCTEUR_INS, FKCOMPTEUR_INS) VALUES ('1', '22.11.2024', '21 Av. de la gare', '1457', 'Walhain', 'SupElec', 'MAISON', 'XVB3G4', 'FU32', 'CG2 ');
--groupe
INSERT INTO TGROUPE (NUM_GRO, FKINSTALLATION_GRO, ORDRE_GRO, FKDISJONCTEUR_GRO) VALUES ('10', '1', '0', 'DG22');
--lignes
INSERT INTO TLIGNE (NUM_LIG, FKGROUPE_LIG, ORDRE_LIG, CODE_LIG, INTERNE_LIG, FKCABLE_LIG, FKFUSIBLE_LIG) VALUES ('1000', '10', '0', NULL, 'true', 'XVB3G2', 'FU22');
INSERT INTO TLIGNE (NUM_LIG, FKGROUPE_LIG, ORDRE_LIG, CODE_LIG, INTERNE_LIG, FKCABLE_LIG, FKFUSIBLE_LIG) VALUES ('1001', '10', '1', NULL, 'true', 'XVB3G2', 'FU22');

--blocs
INSERT INTO TBLOC (NUM_BLO, FKLIGNE_BLO, ORDRE_BLO) VALUES ('10000', '1000', '0');
INSERT INTO TBLOC (NUM_BLO, FKLIGNE_BLO, ORDRE_BLO) VALUES ('10001', '1000', '1');
INSERT INTO TBLOC (NUM_BLO, FKLIGNE_BLO, ORDRE_BLO) VALUES ('10010', '1001', '0');
INSERT INTO TBLOC (NUM_BLO, FKLIGNE_BLO, ORDRE_BLO) VALUES ('10011', '1001', '1');

--blocAPP
INSERT INTO TBLOCAPP (FKAPPAREIL_BAP, FKBLOC_BAP, ORDRE_BAP, CLASSE_BAP) VALUES ('PC11', '10000', '0', 'PRISE');
INSERT INTO TBLOCAPP (FKAPPAREIL_BAP, FKBLOC_BAP, ORDRE_BAP, CLASSE_BAP) VALUES ('PC11', '10000', '1', 'PRISE');
INSERT INTO TBLOCAPP (FKAPPAREIL_BAP, FKBLOC_BAP, ORDRE_BAP, CLASSE_BAP) VALUES ('IC1 ', '10001', '0', 'INTERRUPTEUR');
INSERT INTO TBLOCAPP (FKAPPAREIL_BAP, FKBLOC_BAP, ORDRE_BAP, CLASSE_BAP) VALUES ('PC11', '10001', '1', 'PRISE');
INSERT INTO TBLOCAPP (FKAPPAREIL_BAP, FKBLOC_BAP, ORDRE_BAP, CLASSE_BAP) VALUES ('PC11', '10010', '0', 'PRISE');
INSERT INTO TBLOCAPP (FKAPPAREIL_BAP, FKBLOC_BAP, ORDRE_BAP, CLASSE_BAP) VALUES ('PC11', '10010', '1', 'PRISE');
INSERT INTO TBLOCAPP (FKAPPAREIL_BAP, FKBLOC_BAP, ORDRE_BAP, CLASSE_BAP) VALUES ('IC1 ', '10011', '0', 'INTERRUPTEUR');
INSERT INTO TBLOCAPP (FKAPPAREIL_BAP, FKBLOC_BAP, ORDRE_BAP, CLASSE_BAP) VALUES ('PC11', '10011', '1', 'PRISE');
--Ajuste compteur si nécessaire
--alter table TINSTALLATION alter NUM_INS RESTART WITh 2;