
DELETE FROM TCABLE;

INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('XVB3G15', '3', 'true', '1.50', 'XVB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('XVB3G2', '3', 'true', '2.50', 'XVB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('XVB5G2', '5', 'true', '2.50', 'XVB  ');
INSERT INTO TCABLE(CODE_CAB,NBCONDUCTEURS_CAB,TERRE_CAB,SECTION_CAB,TYPE_CAB) VALUES ('XVB3G4','3','true','4.00','XVB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('XVB4G4', '4', 'true', '4.00', 'XVB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('XVB5G4', '5', 'true', '4.00', 'XVB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('XVB3G6', '3', 'true', '6.00', 'XVB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB15', '1', 'false', '1.50', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB2', '1', 'false', '2.50', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB4', '1', 'false', '4.00', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB6', '1', 'false', '6.00', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB35GG', '1', 'true', '16.00', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB3G15', '3', 'true', '1.50', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB3G2', '3', 'true', '2.50', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB3G4', '3', 'true', '4.00', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB4G15', '4', 'true', '1.50', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB4G2', '4', 'true', '2.50', 'VOB  ');
INSERT INTO TCABLE (CODE_CAB, NBCONDUCTEURS_CAB, TERRE_CAB, SECTION_CAB, TYPE_CAB) VALUES ('VOB4G4', '4', 'true', '4.00', 'VOB  ');



